### ISSUE TITLE
Add references blok

### ISSUE THREAD

**Issue by mraerino** [BILDQUADRAT/website#2]
Not really in the theme, but should be a row with cards in columns.

Fields:
- Picture
- Customer
- Description (markdown)

**Comment by NeoLegends** [comment]
Got any demo content? What kind of pictures will be shown (company logos, pictures snapped during the making, etc.)?

**Comment by mraerino** [comment]
Somewhat like this:
https://www.plazamedia.com/cases/

Should allow linking to any page

**Comment by NeoLegends** [comment]
Tiles seem like the perfect fit for this already, no?

**Comment by mraerino** [comment]
The tiles are currently used for category overviews. I'd be happy if they were only used for that.
Can't we do cards with thumbnails and some text? Should not be too hard to produce custom styling for that.

**Comment by NeoLegends** [comment]
Surely we can, but the theme doesn't have the notion of depth right now. Cards would break that philosophy.

**Comment by mraerino** [comment]
probably don't give them a shadow but rather just use a different background-color for the text

**Comment by NeoLegends** [comment]
Fixed.
